---
- name: Install OpenSSH server
  ansible.builtin.package:
    name: openssh-server
    state: present

- name: Deploy sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart SSH

- name: Ensure SSH service is enabled and running
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started
