---
traefik_image: "traefik"
traefik_tag: "v3.6.1"

traefik_base_dir: "/opt/traefik"
traefik_data_dir: "/mnt/docker/traefik"

traefik_network: "traefik"

traefik_dashboard_domain: "proxy.local.rwdevs.com"

traefik_acme_email: "srdevlead@outlook.com"
traefik_acme_resolver: "cloudflare"

cloudflare_dns_api_token: "{{ lookup('env', 'CF_DNS_API_TOKEN') }}"
