---
# Portainer defaults
portainer_image: "portainer/portainer-ce"
portainer_tag: "latest"

portainer_base_dir: "{{ docker_base_dir }}/portainer"
portainer_data_dir: "{{ docker_base_mnt }}/portainer/data"

portainer_watchtower_enable: "true"
portainer_healthcheck_interval: "30s"
portainer_healthcheck_timeout: "10s"
portainer_healthcheck_retries: 3

# Session timeout in hours (default is 8 hours)
portainer_session_timeout: 24
