---
- name: Configure Base Server
  hosts: all
  become: yes
  # new_hostname can be overridden per host in inventory, defaults to inventory_hostname in role
  # users_to_create:
  #   - name: youruser
  #     groups: sudo,docker
  #     ssh_key: "ssh-rsa AAAA..." # Put actual public key here

  roles:
    - system_base/hostname
    # - system_base/users
    - system_base/security
    # - system_base/ssh
