---
- name: Test Infisical Secret Retrieval
  hosts: localhost
  # become: true

  roles:
    - infisical_secrets

  tasks:
    - name: Show all retrieved secrets under root (human readable)
      debug:
        msg: "Test 1 {{ secrets.root | default({}) | to_nice_yaml }}"
      when: secrets is defined and secrets.root is defined

    - name: "Debug: show raw read_results object"
      debug:
        msg: "Test 2 read_results = {{ read_results | to_nice_yaml }}"
      when: read_results is defined

    - name: "Debug: show read_results.results entries"
      debug:
        msg: "Test 3 read_results.results = {{ read_results.results | to_nice_yaml }}"
      when: read_results is defined and read_results.results is defined

    - name: "Debug: show merged secrets fact"
      debug:
        msg: " Test 4 merged secrets = {{ secrets | to_nice_yaml }}"
      when: secrets is defined

    - name: "Debug: show secret by namespace 1"
      debug:
        msg: " Test 5 OUTLOOK_MAIL_USER = {{ secrets['ansible.mail']['OUTLOOK_MAIL_USER'] | to_nice_yaml }}"
      when: secrets is defined and ('ansible.mail' in secrets) and ('OUTLOOK_MAIL_USER' in secrets['ansible.mail'])

    - name: "Debug: show secret by namespace 2"
      debug:
        msg: "Test 6 SECRET = {{ secrets.SECRET | to_nice_yaml }}"
      when: secrets is defined and ('SECRET' in secrets)
# TODO create secrets universal app to gather secrets for all that need it
# https://infisical.com/docs/integrations/platforms/ansible#universal-auth
