- name: Deploy Lab Package Monitor
  hosts: docker_hosts
  become: true

  vars:
    infisical_secret_paths:
      - "/"
      - "/shared"
      - "/ansible"
      - "/ansible/cloudflare"
      - "/ansible/homarr"
      - "/ansible/homeassistant"
      - "/ansible/mail"
      - "/ansible/mailrise"
      - "/ansible/pihole"
      - "/ansible/portainer"
      - "/ansible/watchtower"

  roles:
    - infisical_secrets
    - apps/watchtower
