---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Configure fail2ban jail.local
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
    content: |
      [DEFAULT]
      bantime = {{ fail2ban_bantime }}
      findtime = {{ fail2ban_findtime }}
      maxretry = {{ fail2ban_maxretry }}

      [sshd]
      enabled = true
  notify: Restart fail2ban

- name: Enable and start fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: yes
    state: started
  when: ansible_facts.packages['fail2ban'] is defined
