---
portainer_version: latest

portainer_base_dir: /opt/containers/portainer
portainer_data_dir: "{{ portainer_base_dir }}/data"

portainer_http_port: 9000
portainer_https_port: 9443

portainer_update: true
