---
new_hostname: prod-docker-01

# Use local storage for PiHole (NFS file locking issues prevent DNS from working)
pihole_base_dir: "/opt/docker/pihole"

# DNS Role: Enable Port 53 binding for production
pihole_bind_dns: true

# Portainer
portainer_agent_dir: "/opt/docker/portainer-agent"
portainer_agent_container_name: "portainer-agent-p01"
portainer_agent_docker_network: "{{ shared_docker_network }}"
portainer_agent_port: 9001
portainer_agent_watchtower_enable: "true"

# Mailrise
mailrise_container_name: mailrise-p01
mailrise_icloud_user: "{{ lookup('env', 'ICLOUD_MAIL_USER') }}"
mailrise_icloud_pass: "{{ lookup('env', 'ICLOUD_MAIL_PASS') }}"
mailrise_icloud_from: "{{ lookup('env', 'ICLOUD_MAIL_FROM') }}"
mailrise_target_email: "{{ lookup('env', 'MAILRISE_EMAIL_DEST') }}"

# Watchtower
watchtower_name: watchtower-p01
watchtower_network: "{{ shared_docker_network }}"
watchtower_email_from: watchtower-p01@rwdevs.com
