# Container
pihole_container_name: pihole
pihole_image: pihole/pihole:latest

# Paths
pihole_base_dir: /opt/docker/pihole

# Locale
pihole_timezone: America/New_York

# Web / DNS
pihole_domain: pihole.local.rwdevs.com
pihole_password: changeme

pihole_dns1: 1.1.1.1
pihole_dns2: 8.8.8.8

# Promotion control
pihole_bind_dns: false # <-- THIS is the key switch

# Integrations
traefik_network: traefik
watchtower_enable: true
