---
- name: Create Portainer Agent directory
  ansible.builtin.file:
    path: "{{ portainer_agent_dir }}"
    state: directory
    owner: "0"
    group: "0"
    mode: "0755"

- name: Deploy Portainer Agent docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_agent_dir }}/docker-compose.yml"
    owner: "0"
    group: "0"
    mode: "0644"

- name: Start Portainer Agent container
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_agent_dir }}"
    state: present
