docker_hosts:
  vars:
    # This sets it for every host in the group
    shared_docker_api_version: "1.44"
    shared_docker_network: "traefik"
  hosts:
    docker-vm01:
      new_hostname: dev-docker-01
      ansible_host: 192.168.50.12
      ansible_user: ka8kgj
      docker_users:
        - ka8kgj

      # PiHole configuration
      pihole_container_name: pihole-d01
      pihole_domain: pihole-d01.local.rwdevs.com
      pihole_password: "{{ lookup('ansible.builtin.env', 'PIHOLE_PASSWORD') }}"
      pihole_bind_dns: true

      # Traefik configuration
      traefik_container_name: "traefik-d01"
      traefik_dashboard_domain: "traefik-d01.local.rwdevs.com"
      traefik_acme_domain_main: "rwdevs.com"
      traefik_acme_domain_sans: "*.rwdevs.com,*.local.rwdevs.com"
      traefik_acme_server: "https://acme-v02.api.letsencrypt.org/directory"
      proxmox_domain: "proxmox.local.rwdevs.com"
      proxmox_url: "https://192.168.50.11:8006"
      traefik_port_http: 80
      traefik_port_https: 443
      traefik_port_api: 8080
      traefik_dns_resolvers:
        - "1.1.1.1:53"
        - "1.0.0.1:53"
      traefik_docker_api_version: "{{ shared_docker_api_version }}"
      traefik_insecure_skip_verify: true
      traefik_hsts_max_age: 15552000
      traefik_ip_whitelist:
        - "10.0.0.0/8"
        - "192.168.50.0/24"
        - "172.18.0.0/16"

      # Portainer configuration
      portainer_container_name: "portainer-d01"
      portainer_domain: "portainer-d01.local.rwdevs.com"
      portainer_docker_network: "{{ shared_docker_network }}"
      portainer_watchtower_enable: "true"

      # Watchtower
      watchtower_name: watchtower-d01
      watchtower_network: "{{ shared_docker_network }}"
      watchtower_notification_url: "smtp://mailrise-d01:8025/?to={{ mailrise_target_email }}&encryption=none"

      # Mailrise
      mailrise_smtp_port: 8025
      mailrise_http_port: 8080
      mailrise_ha_host: "192.168.50.12"
      mailrise_target_email: "AlertsRWD@outlook.com"
      mailrise_container_name: mailrise-d01

      # Homepage service variables (used in services.yaml.j2)
      homepage_container_name: "homepage-d01"
      homepage_domain: "homepage-d01.local.rwdevs.com"
      homepage_var_pihole_url: "https://pihole.local.rwdevs.com"
      homepage_var_proxy_url: "https://traefik.local.rwdevs.com"
      homepage_var_proxy_password: "{{ lookup('env', 'HOMEPAGE_PROXY_PASSWORD') }}"
      homepage_var_proxmox_url: "https://proxmox.local.rwdevs.com:8006"
      homepage_var_proxmox_user: "admin@pam"
      homepage_var_proxmox_api_key: "{{ lookup('env', 'HOMEPAGE_PROXMOX_API_KEY') }}"
      homepage_var_truenas_url: "https://truenas.local.rwdevs.com"
      homepage_var_truenas_key: "{{ lookup('env', 'HOMEPAGE_TRUENAS_KEY') }}"
      homepage_var_omv_url: "https://omv.local.rwdevs.com"
      homepage_var_omv_usr: "admin"
      homepage_var_omv_pwd: "{{ lookup('env', 'HOMEPAGE_OMV_PASSWORD') }}"
      homepage_var_portainer_dev_url: "https://portainer-dev.local.rwdevs.com"
      homepage_var_portainer_dev_key: "{{ lookup('env', 'HOMEPAGE_PORTAINER_DEV_KEY') }}"

# Grouping for easy playbook targeting
portainer:
  children: docker_hosts
