docker_hosts:
  hosts:
    dev-docker-01:
      ansible_host: 192.168.50.12
      ansible_user: ka8kgj
      mailrise_ip: 192.168.50.12
      alert_email: alerts@mailrise.xyz
    prod-docker-01:
      ansible_host: 192.168.50.14
      ansible_user: ka8kgj
      mailrise_ip: 192.168.50.12
      alert_email: alerts@mailrise.xyz

portainer:
  children:
    docker_hosts:
